include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - always_declare_return_types
    - omit_local_variable_types
    - prefer_final_locals
    - prefer_relative_imports
    - prefer_single_quotes
    - sort_child_properties_last
    - sort_constructors_first
    - type_annotate_public_apis
    - unawaited_futures
analyzer:
  errors:
    deprecated_member_use_from_same_package: warning
